backend:
  name: git-gateway
  branch: master
  repo: LauraBrandt/test-hugo-netlifycms

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "test"
    label: "Test Post"
    folder: "content/test"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Boolean", name: "boolean", widget: "boolean", required: false}
      - {label: "Text", name: "text", widget: "text", required: false}
      - {label: "Number", name: "number", widget: "number", required: false}
      - {label: "Markdown", name: "markdown", widget: "markdown", required: false}
      - {label: "Datetime", name: "datetime", widget: "datetime", required: false}
      - {label: "Date", name: "date", widget: "date", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "File", name: "file", widget: "file", required: false}
      - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"], required: false}
      - {label: "Hidden", name: "hidden", widget: "hidden", default: "hidden", required: false}
  - name: "lists"
    label: "List Test"
    folder: "content/list"
    create: true
    fields:
      - {label: "Title", name: title, widget: string}
      - {label: "Comma List", name: commaList, widget: list, required: false}
      - {label: "Nested List Multiple", name: nestedListMultiple, widget: list, fields: [{label: Name, name: name, widget: string}, {label: Description, name: description, widget: string}], required: false}
      - {label: "Nested List Single", name: nestedListSingle, widget: list, fields: [{label: Name, name: name, widget: string}], required: false}
      - {label: "Nested List Single Field", name: nestedListSingleField, widget: list, field: [{label: Name, name: name, widget: string}], required: false}
      - {label: "List Boolean", name: listBoolean, widget: list, fields: [{label: bool1, name: bool1, widget: boolean}, {label: bool2, name: bool2, widget: boolean}], required: false}
      - {label: "List Boolean Single", name: listBooleanSingle, widget: list, fields: [{label: bool1, name: bool1, widget: boolean}], required: false}
      - {label: "Text List", name: textList, widget: list, fields: [{label: textitem, name: textitem, widget: text}], required: false}
      - {label: "Number List", name: numberList, widget: list, fields: [{label: "number item", name: numberitem, widget: number}], required: false}
      - {label: "Select List", name: selectList, widget: list, fields: [{label: "select item", name: selectitem, widget: select, options: ["a", "b"]}], required: false}
      - {label: "Markdown List", name: markdownList, widget: list, fields: [{label: "markdown item", name: markdownitem, widget: markdown}], required: false}
      - {label: "Image List", name: imageList, widget: list, fields: [{label: "image", name: imageitem, widget: image}, {label: "alt-text", name: altitem, widget: string}], required: false}
      - {label: "File List", name: fileList, widget: list, fields: [{label: "file name", name: filenameitem, widget: string}, {label: "file", name: fileitem, widget: file}], required: false}
      - {label: "Date List", name: dateList, widget: list, fields: [{label: "date", name: dateitem, widget: date}], required: false}
  - name: "objects"
    label: "Object Test"
    folder: "content/object"
    create: true
    fields:
      - {label: "Title", name: title, widget: string}
      - {label: "Object string", name: objectString, widget: "object", fields: [{label: "description", name: description, widget: string}], required: false }
      - {label: "Object date", name: objectDate, widget: "object", fields: [{label: "Date", name: date, widget: date}], required: false }
  - name: "datelist"
    label: "Only Date List Test"
    folder: "content/datelist"
    create: true
    fields:
      - {label: "Title", name: title, widget: string}
      - {label: "Date List", name: dateList, widget: list, fields: [{label: "date", name: dateitem, widget: date}], required: false}
